// WebSite/site-react/components/Footer.tsx
import * as React from "react";
import Link from "next/link";
import { TinyAssetsMark } from "./TinyAssetsMark";
import legal from "../lib/legal-info.json";
import styles from "./Footer.module.css";

export function Footer() {
  const year = 2026;
  const contact = (legal as any)?.contact ?? {};
  return (
    <footer className={styles.footer}>
      <div className={`container ${styles.naming}`}>
        <div className={styles.brand}>
          <TinyAssetsMark size={22} />
          <p className={styles.namingText}>
            <strong>Tiny</strong> is the public face of <strong>TinyAssets</strong> — an open-source
            engine that runs real multi-step work for any goal. He lives at{" "}
            <span className="ev">tinyassets.io</span>; his code lives on{" "}
            <a href="https://github.com/Jonnyton/TinyAssets" target="_blank" rel="noreferrer">GitHub</a>.
          </p>
        </div>
      </div>

      <div className={`container ${styles.grid}`}>
        <div className={styles.col}>
          <span className="eyebrow">Use him</span>
          <ul>
            <li><Link href="/start">Start — connect a chatbot</Link></li>
            <li><Link href="/goals">Goals — what&apos;s being worked on</Link></li>
            <li><Link href="/host">Host a daemon</Link></li>
            <li><Link href="/alliance">Work with us</Link></li>
          </ul>
        </div>
        <div className={styles.col}>
          <span className="eyebrow">Watch him</span>
          <ul>
            <li><Link href="/loop">The loop — how he patches himself</Link></li>
            <li><Link href="/commons">Commons — the public brain</Link></li>
            <li><Link href="/graph">Graph — the whole map</Link></li>
            <li><Link href="/fine-print">Vital signs &amp; fine print</Link></li>
          </ul>
        </div>
        <div className={styles.col}>
          <span className="eyebrow">Build him</span>
          <ul>
            <li><Link href="/build">Contribute</Link></li>
            <li><Link href="/soul">Fork the pattern — souls</Link></li>
            <li><a href="https://github.com/Jonnyton/TinyAssets" target="_blank" rel="noreferrer">GitHub ↗</a></li>
            <li><a href="https://github.com/Jonnyton/TinyAssets/blob/main/PLAN.md" target="_blank" rel="noreferrer">PLAN.md ↗</a></li>
          </ul>
        </div>
        <div className={styles.col}>
          <span className="eyebrow">Fine print</span>
          <ul>
            <li><Link href="/legal">Terms &amp; privacy</Link></li>
            <li><Link href="/legal#token-disclosures">Token disclosures</Link></li>
            <li><Link href="/legal#risk-factors">Risk factors</Link></li>
            <li><Link href="/legal#dmca">DMCA</Link></li>
          </ul>
        </div>
      </div>

      <div className={`container ${styles.supply}`}>
        <p className={styles.supplyLine}>
          Money note, in one honest sentence: work and credit settle on a{" "}
          <em>test rail</em> today — no real currency moves here, and nothing on
          this site is investment advice. <Link href="/legal#token-disclosures">Disclosures →</Link>
        </p>
      </div>

      <div className={`container ${styles.bottom}`}>
        <span>© {year} Tiny Assets · MIT + CC0 · concept-public, instance-private</span>
        <span className={styles.contact}>
          {contact.general && <a href={`mailto:${contact.general}`}>{contact.general}</a>}
          {contact.general && contact.security && " · "}
          {contact.security && <a href={`mailto:${contact.security}`}>{contact.security}</a>}
        </span>
      </div>
    </footer>
  );
}

export default Footer;

// WebSite/site/src/lib/components/Footer.svelte
<!--
  Footer — full index + the one canonical naming sentence.
  Every built page is reachable from here; nothing orphaned. The token
  line is one honest sentence pointing at disclosures, not a wallet rack.
-->
<script lang="ts">
  import WorkflowMark from './WorkflowMark.svelte';
  import legal from '$lib/content/legal-info.json';

  const year = new Date().getFullYear();
</script>

<footer class="footer">
  <div class="container footer__naming">
    <div class="brand">
      <WorkflowMark size={22} />
      <p class="naming">
        <strong>Tiny</strong> is the public face of <strong>Workflow</strong> — an open-source
        engine that runs real multi-step work for any goal. He lives at
        <span class="ev">tinyassets.io</span>; his code lives on
        <a href="https://github.com/Jonnyton/Workflow" target="_blank" rel="noreferrer">GitHub</a>.
        Same thing, one body, two names.
      </p>
    </div>
  </div>

  <div class="container footer__grid">
    <div class="col">
      <span class="eyebrow">Use him</span>
      <ul>
        <li><a href="/start">Start — connect a chatbot</a></li>
        <li><a href="/goals">Goals — what's being worked on</a></li>
        <li><a href="/host">Host a daemon</a></li>
        <li><a href="/alliance">Work with us</a></li>
      </ul>
    </div>
    <div class="col">
      <span class="eyebrow">Watch him</span>
      <ul>
        <li><a href="/loop">The loop — how he patches himself</a></li>
        <li><a href="/commons">Commons — the public brain</a></li>
        <li><a href="/graph">Graph — the whole map</a></li>
        <li><a href="/fine-print">Vital signs &amp; fine print</a></li>
      </ul>
    </div>
    <div class="col">
      <span class="eyebrow">Build him</span>
      <ul>
        <li><a href="/build">Contribute</a></li>
        <li><a href="/soul">Fork the pattern — souls</a></li>
        <li><a href="https://github.com/Jonnyton/Workflow" target="_blank" rel="noreferrer">GitHub ↗</a></li>
        <li><a href="https://github.com/Jonnyton/Workflow/blob/main/PLAN.md" target="_blank" rel="noreferrer">PLAN.md ↗</a></li>
      </ul>
    </div>
    <div class="col">
      <span class="eyebrow">Fine print</span>
      <ul>
        <li><a href="/legal">Terms &amp; privacy</a></li>
        <li><a href="/legal#token-disclosures">Token disclosures</a></li>
        <li><a href="/legal#risk-factors">Risk factors</a></li>
        <li><a href="/legal#dmca">DMCA</a></li>
      </ul>
    </div>
  </div>

  <div class="container footer__supply">
    <p class="supply-line">
      Money note, in one honest sentence: work and credit settle on a
      <em>test rail</em> today — no real currency moves here, and nothing on
      this site is investment advice. <a href="/legal#token-disclosures">Disclosures →</a>
    </p>
  </div>

  <div class="container footer__bottom">
    <span>© {year} Tiny Assets · MIT + CC0 · concept-public, instance-private</span>
    <span class="contact">
      <a href="mailto:{legal.contact.general}">{legal.contact.general}</a> ·
      <a href="mailto:{legal.contact.security}">{legal.contact.security}</a>
    </span>
  </div>
</footer>

<style>
  .footer {
    border-top: 1px solid var(--border-1);
    background: var(--bg-2);
    padding-block: var(--s-8) var(--s-5);
    margin-top: var(--s-16);
  }
  .footer__naming { padding-bottom: var(--s-5); border-bottom: 1px solid var(--border-1); }
  .brand { display: flex; align-items: flex-start; gap: 12px; }
  .naming {
    margin: 0;
    font-family: var(--font-voice);
    font-size: 15px;
    line-height: 1.6;
    color: var(--fg-2);
    max-width: 72ch;
  }
  .naming strong { color: var(--fg-1); font-weight: 600; }

  .footer__grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 24px;
    padding: var(--s-6) 0;
    border-bottom: 1px solid var(--border-1);
  }
  @media (max-width: 700px) { .footer__grid { grid-template-columns: repeat(2, 1fr); } }
  .col ul { list-style: none; padding: 0; margin: 12px 0 0; display: flex; flex-direction: column; gap: 8px; }
  .col li a { color: var(--fg-2); text-decoration: none; font-size: 13px; }
  .col li a:hover { color: var(--ember-700); text-decoration: underline; }

  .footer__supply { padding: var(--s-5) 0; border-bottom: 1px solid var(--border-1); }
  .supply-line { margin: 0; font-size: 13px; color: var(--fg-3); max-width: 80ch; }
  .supply-line em { font-style: italic; color: var(--fg-2); }

  .footer__bottom {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    gap: 12px;
    margin-top: var(--s-4);
    font-family: var(--font-mono);
    font-size: 11px;
    color: var(--fg-3);
  }
  .contact a { color: var(--fg-2); text-decoration: none; }
  .contact a:hover { color: var(--ember-700); }
</style>
